[defaults]
; max_seconds = 60
; reqs_per_sec = 1.5
; max_threads = 8
; max_resource_threads = 2
; host_timeout_threshold = 3
; host_cooldown_seconds = 60
; max_file_size_mb = 0
; min_free_disk_mb = 512
; min_free_disk_percent = 2
; save_raw_data = false
; extract_schema = true

[datosgobes]
; reqs_per_sec = 5

[zenodo]
; reqs_per_sec = 1.3889

[Soda]
token =

[Zenodo]
token =

[CKAN]
token =
